name: Deploy

on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd apps/QuidX-dev
          git pull origin dev
          git status
          yarn install --only=prod --frozen-lockfile
          npx prisma migrate deploy --schema prisma/postgres/schema.prisma
          yarn build
          pm2 restart dev

